"""CVE-remediation prompt for Devin sessions.

The prompt is uv-aware: Superset's `requirements/base.txt` is autogenerated.
Telling Devin to edit it directly would fight the next regeneration. The
correct mental model is "edit pyproject.toml, then regenerate base.txt with
uv pip compile."

Issue body parser lives here too — it reads the structured format that
file_issues.py emits, so the two stay in lockstep.
"""
from __future__ import annotations

import re
from dataclasses import dataclass


@dataclass(frozen=True)
class CveContext:
    cve_id: str
    package: str
    installed_version: str
    fix_version: str
    severity: str
    summary: str
    issue_url: str
    issue_number: int


# Issue body format produced by file_issues.py:
#   ## Vulnerability
#   - **CVE:** CVE-2026-XXXXX
#   - **Package:** flask
#   - **Installed:** 2.3.3
#   - **Fix version:** 3.1.3
#   - **Severity:** LOW
#   - **Summary:** ...
_FIELD = re.compile(r"^\s*-\s*\*\*([A-Za-z ]+):\*\*\s*(.+?)\s*$", re.MULTILINE)


def parse_issue_to_cve_context(issue: dict) -> CveContext | None:
    """Parse a GitHub issue payload into a CveContext, or None if it doesn't
    look like a CVE issue we filed.

    Loose parser by design — if a field is missing we still return the best
    effort, and the caller can decide what to do. Returns None only if the
    minimum (cve_id + package) can't be found.
    """
    body = issue.get("body") or ""
    fields = {m.group(1).strip().lower(): m.group(2).strip() for m in _FIELD.finditer(body)}

    cve_id = fields.get("cve")
    package = fields.get("package")
    if not (cve_id and package):
        return None

    return CveContext(
        cve_id=cve_id,
        package=package,
        installed_version=fields.get("installed", "unknown"),
        fix_version=fields.get("fix version", "latest"),
        severity=fields.get("severity", "UNKNOWN"),
        summary=fields.get("summary", ""),
        issue_url=issue.get("html_url", ""),
        issue_number=issue.get("number", 0),
    )


def cve_id_slug(cve_id: str) -> str:
    """For branch names — keep alnum and dashes only."""
    return re.sub(r"[^A-Za-z0-9-]", "-", cve_id).lower()


def build_cve_prompt(ctx: CveContext, *, fork_url: str) -> str:
    branch = f"devin/cve-{cve_id_slug(ctx.cve_id)}"
    return f"""You are remediating a security vulnerability in the fork at {fork_url}.

VULNERABILITY:
- CVE: {ctx.cve_id}
- Package: {ctx.package} {ctx.installed_version}
- Fix version available: {ctx.fix_version}
- Severity: {ctx.severity}
- Summary: {ctx.summary}
- Source issue: {ctx.issue_url}

CONTEXT — DEPENDENCY MANAGEMENT IN THIS REPO:
This repo uses `uv` to compile its requirements files. The hierarchy is:
- `pyproject.toml` — source of truth for direct dependencies and version bounds
- `requirements/base.in` — additional pinned constraints layered on top
- `requirements/base.txt` — AUTOGENERATED by:
    uv pip compile pyproject.toml requirements/base.in -o requirements/base.txt
  DO NOT edit `base.txt` by hand. Any direct edits will be wiped on the next
  regeneration. Update the source files, then regenerate.

YOUR TASK:
1. Create a branch `{branch}` off `master`.
2. Locate where `{ctx.package}` is constrained:
   - If it appears in `pyproject.toml`'s `dependencies` array, widen or update
     the version bound there to include `>={ctx.fix_version}`.
   - If it only appears as a transitive constraint in `requirements/base.in`,
     update there.
   - If it's purely transitive (no explicit pin), find the direct dependency
     that pulls it in and update that direct dep to a version whose own
     dependency resolves to >={ctx.fix_version}.
3. Run `uv pip compile pyproject.toml requirements/base.in -o requirements/base.txt`
   to regenerate the lock file. Commit BOTH the source file(s) you edited AND
   the regenerated `requirements/base.txt` in the same commit.
4. Run the test suite. If any tests fail because of the upgrade, fix them with
   the smallest possible change. Do not refactor.
5. Open a pull request against `master` with:
   - Title: "Security: upgrade {ctx.package} to {ctx.fix_version} ({ctx.cve_id})"
   - Description: link to the source issue ({ctx.issue_url}), summary of changes,
     and the test results.
   - Reference issue #{ctx.issue_number} so it auto-closes on merge.

CONSTRAINTS:
- Modify only what is required for this CVE. No drive-by improvements.
- Do not bump unrelated dependencies in `pyproject.toml`.
- If the fix version is outside Superset's currently allowed range and you
  cannot widen the bound safely, open the PR as DRAFT and explain the
  blocker in the description.
- If you discover the package has no actual usage in the codebase, document
  that — removal is a valid fix.

ACCEPTANCE:
- CI is green on the resulting PR.
- No new lint or type errors.
- `pyproject.toml` and `requirements/base.txt` are internally consistent
  (a fresh `uv pip compile` would produce no diff).
"""
